spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
    url: jdbc:postgresql://localhost:5432/username
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comment: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: info