version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

volumes:
  postgresql-volume: